home/urls.py
from django.urls import re_path

from . import views
from skka.settings import DEBUG

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^about/$', views.about, name='about'),
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^logout/$', views.logout, name='logout'),
    re_path(r'^carousel/$', views.carousel_manager, name='carousel'),
    re_path(r'^carousel/upload/', views.carousel_upload, name='carousel-upload'),
    re_path(r'^carousel/reorder/', views.carousel_reorder, name='carousel-reorder'),
    re_path(r'^carousel/delete/(?P<img_id>[1-9]\d*)/', views.carousel_delete, name='carousel-delete'),
]

if DEBUG:
    urlpatterns += [
        re_path(r'^400/$', views.handler400),
        re_path(r'^403/$', views.handler403),
        re_path(r'^404/$', views.handler404),
        re_path(r'^500/$', views.handler500),
    ]

skka/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf.urls import (
    handler400,
    handler403,
    handler404,
    handler500,
)
from django.conf.urls.static import static

from skka.settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    re_path(r'^', include(('home.urls', 'home'), namespace='home')),
    re_path(r'^gallery/', include(('gallery.urls', 'gallery'), namespace='gallery')),
    re_path(r'^admin/', admin.site.urls),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

handler400 = 'home.views.handler400'
handler403 = 'home.views.handler403'
handler404 = 'home.views.handler404'
handler500 = 'home.views.handler500'

home/models.py
import hashlib
import os

from base64 import b16encode
from functools import partial
from io import BytesIO
from PIL import Image

from django.db import models
from django.db.models.signals import pre_init

from skka.settings import TZ, MEDIA_ROOT

class TimestampedModel(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    @property
    def updated_later(self):
        return self.date_updated.astimezone(TZ).replace(hour=0, minute=0, second=0, microsecond=0) > self.date_created.astimezone(TZ).replace(hour=0, minute=0, second=0, microsecond=0)

    class Meta:
        abstract = True

class ThumbnailedImage(TimestampedModel):
    image = models.ImageField(blank=True, null=True, default=None, upload_to='')
    _image_hash = models.BinaryField(editable=False, null=True, default=None, max_length=16)
    thumbnail = models.ImageField(blank=True, null=True, default=None, upload_to='')
    _thumbnail_hash = models.BinaryField(editable=False, null=True, default=None, max_length=16)

    @classmethod
    def create(cls, *args, **kwargs):
        image = cls(**kwargs)
        image.image_ops()

        return image

    def __str__(self):
        return self.image.name

    def image_ops(
        self, relative_path='', max_size=(960, 720),
        thumbnail_size=(100, 100),
    ):
        self._generate_thumbnail(relative_path, thumbnail_size)
        self._hash_thumbnail(relative_path)
        self._resize_image(relative_path, max_size)
        self._hash_image(relative_path)

    def _generate_thumbnail(self, relative_path, thumbnail_size):
        img = Image.open(self.image).convert('RGB')
        width, height = img.size
        max_longest, max_shortest = thumbnail_size

        if not self.thumbnail and (width >= height and (width > max_longest or height > max_shortest)) or (height > width and (height > max_longest or width > max_shortest)):
            if width > height:
                if (height * max_longest/ width) > max_shortest:
                    new_height = max_shortest
                    new_width = int(width * new_height / height)
                else:
                    new_width = max_longest
                    new_height = int(height * new_width / width)
            else:
                if (width * max_longest / height) > max_shortest:
                    new_width = max_shortest
                    new_height = int(height * new_width / width)
                else:
                    new_height = max_longest
                    new_width = int(width * new_height / height)

            img = img.resize((new_width, new_height), Image.ANTIALIAS)

        img_file = BytesIO()
        img.save(img_file, 'JPEG', quality=90)

        new_name = 'thumbnail_' + self.image.name.split('.')[0].replace(relative_path, '') + '.jpg'
        self.thumbnail.save(new_name, img_file)

    def _hash_thumbnail(self, relative_path, block_size=65536):
        hasher = hashlib.md5()
        filename = MEDIA_ROOT + '/' + self.thumbnail.name

        with open(filename, 'rb') as f:
            for buf in iter(partial(f.read, block_size), b''):
                hasher.update(buf)

            if not self.thumbnail_hash or self.thumbnail_hash != hasher.hexdigest().lower():
                self._thumbnail_hash = hasher.digest()
                self.thumbnail.name = relative_path + hasher.hexdigest().lower() + '.jpg'
                new_filename = MEDIA_ROOT + '/' + self.thumbnail.name
                os.rename(filename, new_filename)

    def _resize_image(self, relative_path, max_size):
        img = Image.open(self.image).convert('RGB')
        width, height = img.size
        max_width, max_height = max_size

        if (width >= height and (width > max_width or height > max_height)) or (height > width and (height > max_height or width > max_width)):
            if width > height:
                if (height * max_width/ width) > max_height:
                    new_height = max_height
                    new_width = int(width * new_height / height)
                else:
                    new_width = max_width
                    new_height = int(height * new_width / width)
            else:
                if (width * max_width / height) > max_height:
                    new_width = max_height
                    new_height = int(height * new_width / width)
                else:
                    new_height = max_width
                    new_width = int(width * new_height / height)

            img = img.resize((new_width, new_height), Image.ANTIALIAS)

        img_file = BytesIO()
        img.save(img_file, 'JPEG', quality=90)

        new_name = self.image.name.split('.')[0].replace(relative_path, '') + '.jpg'
        self.image.delete()
        self.image.save(new_name, img_file)

    def _hash_image(self, relative_path, block_size=65536):
        hasher = hashlib.md5()
        filename = MEDIA_ROOT + '/' + self.image.name

        with open(filename, 'rb') as f:
            for buf in iter(partial(f.read, block_size), b''):
                hasher.update(buf)

            if not self.image_hash or self.image_hash != hasher.hexdigest().lower():
                self._image_hash = hasher.digest()
                self.image.name = relative_path + hasher.hexdigest().lower() + '.jpg'
                new_filename = MEDIA_ROOT + '/' + self.image.name
                os.rename(filename, new_filename)

    @property
    def image_hash(self):
        return str(b16encode(self._image_hash).lower(), 'utf-8') if self._image_hash else None

    @property
    def thumbnail_hash(self):
        return str(b16encode(self._thumbnail_hash).lower(), 'utf-8') if self._thumbnail_hash else None

    class Meta:
        abstract = True

class CarouselImage(ThumbnailedImage):
    image = models.ImageField(blank=True, null=True, default=None, upload_to='carousel/')
    thumbnail = models.ImageField(blank=True, null=True, default=None, upload_to='carousel/')

    def image_ops(self):
        super().image_ops(relative_path='carousel/', max_size=(800, 600))

home/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import CarouselImage

class UserForm(forms.Form):
    username = forms.CharField(
        label='',
        max_length=150,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Username',
        }),
    )
    password = forms.CharField(
        label='',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Password',
        })
    )

class CarouselForm(forms.ModelForm):
    images = forms.ImageField(
        label='Images',
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
    )

    def clean(self):
        super().clean()
        return self.cleaned_data

    class Meta:
        model = CarouselImage
        fields = ['image']

home/views.py
import json

from datetime import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import (
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseNotFound,
)
from django.shortcuts import (
    redirect,
    render,
    get_object_or_404,
)
from django.urls import reverse

from .forms import UserForm, CarouselForm
from .models import CarouselImage
from skka.settings import TZ, NAME

def handler400(request, exception=None):
    return render(request, 'home/error/400.html', status=400)

def handler403(request, exception=None):
    return render(request, 'home/error/403.html', status=403)

def handler404(request, exception=None):
    return render(request, 'home/error/404.html', status=404)

def handler500(request, exception=None):
    return render(request, 'home/error/500.html', status=500)

def index(request):
    return render(request, 'home/index.html', {
        'images': CarouselImage.objects.all().order_by('date_updated'),
        'year': datetime.now(TZ).year,
        'name': NAME,
    })

def login(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            messages.info(request, 'You have been redirected to the homepage as you are already logged in.')

            return redirect('home:index')

        return render(request, 'home/login.html', {
            'form': UserForm(),
            'year': datetime.now(TZ).year,
            'name': NAME,
        })
    elif request.method == 'POST':
        form = UserForm(request.POST)

        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )

            if user is None:
                messages.error(request, 'The username/password combination you entered does not match any user in our database. Please try again.')

                return redirect('home:login')

            dj_login(request, user)

            messages.success(request, 'Welcome back%s!' % (', %s' % user.first_name if user.first_name else ''))

            return redirect('home:index')

        messages.error(request, 'There was an error logging in. Please try again.')

        return redirect('home:login')

    return HttpResponseBadRequest()

def logout(request):
    if request.method != 'GET':
        return HttpResponseBadRequest()

    dj_logout(request)

    messages.success(request, 'You have successfully logged out. We hope to see you again soon!')

    return redirect('home:index')

def carousel_manager(request):
    if not (request.method == 'GET' and request.user.is_superuser):
        return HttpResponseBadRequest()

    return render(request, 'home/carousel_manager.html', {
        'images': CarouselImage.objects.all().order_by('date_updated'),
        'year': datetime.now(TZ).year,
        'name': NAME,
    })

def carousel_upload(request):
    if not request.user.is_superuser:
        return HttpResponseBadRequest()

    if request.method == 'GET':
        return render(request, 'home/carousel_upload.html', {
            'form': CarouselForm(),
            'year': datetime.now(TZ).year,
            'name': NAME,
        })
    elif request.method == 'POST':
        form = CarouselForm(request.POST, request.FILES)

        if form.is_valid():
            images = request.FILES.getlist('images')
            for img in images:
                image = CarouselImage.create(image=img)
                image.save()

            images_len = len(images)
            messages.success(request, 'You have successfully added %d image%s to the carousel. <a href="%s">Click here</a> to see the updated carousel.' % (images_len, '' if images_len == 1 else 's', reverse('home:index')), extra_tags='safe')

            return redirect('home:carousel-upload')

        messages.error(request, 'There was an error adding the image to the carousel.')

        return redirect('home:carousel-upload')

    return HttpResponseBadRequest()

def carousel_reorder(request):
    if not (request.method == 'GET' and request.user.is_superuser):
        return HttpResponseBadRequest()

    # retrieve lists
    order = json.loads(request.GET.get('order', '[]'))
    images = CarouselImage.objects.all()

    # validate input
    for img in images:
        if img.id not in order:
            messages.error(request, 'There was an error reordering the carousel images. At least one of the images specified could not be found.')

            return HttpResponseNotFound()

    # touch images in order
    for img_id in order:
        CarouselImage.objects.get(id=img_id).save()

    messages.success(request, 'You have successfully reordered the carousel images. <a href="%s">Click here</a> to see the updated carousel.' % reverse('home:index'), extra_tags='safe')

    return HttpResponse(status=200)

def carousel_delete(request, img_id):
    if not (request.method == 'GET' and request.user.is_superuser):
        return HttpResponseBadRequest()

    img = get_object_or_404(CarouselImage, id=img_id)
    img.delete()

    messages.success(request, 'You have successfully deleted the carousel image.')

    return redirect('home:carousel')

def about(request):
    if request.method != 'GET':
        return HttpResponseBadRequest()

    return render(request, 'home/about.html', {
        'year': datetime.now(TZ).year,
        'name': NAME,
    })

home/templates/home/about.html
{% extends 'home/base.html' %}
{% block content %}
<div id="gradientTop" class="sticky-top"></div>
<section class="container">
  <h3 class="h3">Susan Kill Kegan, Registered Landscape Architect</h3>
  <a data-fancybox="gallery" href="{% load static %}{% static 'home/img/susan.jpg' %}">
    <img class="block-image" src="{% static 'home/img/susan.jpg' %}" alt="Susan with some helpers">
  </a>
  <p class="text-justify">Listening closely to clients to determine their objectives, Susan Kill Kegan designs landscapes that complement existing architecture and incorporates site conditions to produce a plan that is unique, functional and beautiful.</p>
  <p class="text-justify">Susan has a Bachelor of Landscape Architecture from the University of Illinois-Urbana and over 30 years of experience in all aspects of landscape architecture and construction. She also donates time and talent in a “pro bono” capacity, serving on several neighborhood committees providing design assistance.</p>
  <h3 class="h3">In the Press</h3>
  <p class="text-justify"><a class="external-link" href="https://www.chicagotribune.com/news/ct-xpm-1999-09-10-9909100356-story.html">Shielding your yard from noise and prying eyes &ndash; The Chicago Tribune</a></p>
  <a data-fancybox="gallery" href="{% static 'home/img/article.jpg' %}">
    <img class="block-image" src="{% static 'home/img/article.jpg' %}" alt="Chicago Tribune article">
  </a>
</section>
{% endblock %}

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Meta Tags -->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Title & Favicon -->
  <title>Susan Kill Kegan &ndash; Registered Landscape Architect</title>
  <link rel="shortcut icon" href="{% load static %}{% static 'home/img/favicon.png' %}" type="image/x-icon">

  <!--------------->
  <!--Stylesheets-->
  <!--------------->

  <!-- Internal Stylesheets (compressed) -->

  <!-- Reset CSS -->
  <link rel="stylesheet" href="{% static 'home/css/reset.min.css' %}">

  <!-- Home App CSS -->
  <link rel="stylesheet" href="{% static 'home/css/home.min.css' %}">

  <!--Internal Stylesheets (uncompressed)-->

  <!-- Reset CSS -->
  <!-- <link rel="stylesheet" href="{% static 'home/css/reset.css' %}"> -->

  <!-- Home App CSS -->
  <!-- <link rel="stylesheet" href="{% static 'home/css/home.css' %}"> -->

  <!-- External Stylesheet Libraries (compressed) -->

  <!-- Font Awesome CSS -->
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!-- fancybox CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css">

  <!----------->
  <!--Scripts-->
  <!----------->

  <!-- External Script Libraries (compressed) -->

  <!-- Font Awesome JS -->
  <script type="text/javascript" src="https://kit.fontawesome.com/3c68f13de5.js"></script>

  <!-- jQuery JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

  <!-- Bootstrap JS -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <!-- fancybox JS -->
  <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>

  <!-- Internal Scripts (compressed) -->

  <!-- Cross-App JS -->
  <script type="text/javascript" src="{% static 'global/js/global.min.js' %}"></script>

  <!-- Internal Scripts (uncompressed) -->

  <!-- Cross-App JS -->
  <!-- <script type="text/javascript" src="{% static 'global/js/global.js' %}"></script> -->
</head>
<body>
  <section id="grid">
    {% include 'home/title.html' %}
    <section id="content">
      {% include 'home/navbar.html' %}
      {% block content %}
      {% endblock %}
      {% include 'home/footer.html' %}
    </section>
  </section>
</body>
</html>

home/templates/home/carousel.html
{% if images %}
<div id="carousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    {% for img in images %}
    <li data-target="#carousel" data-slide-to="{{ forloop.counter0 }}"{% if forloop.first %} class="active"{% endif %}></li>
    {% endfor %}
  </ol>
  <div class="carousel-inner">{% load static %}
    {% for img in images %}
    <div class="carousel-item{% if forloop.first %} active{% endif %}">
      <img class="d-block" src="{{ img.image.url }}" alt="Carousel slide">
    </div>
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<script src="{% static 'home/js/carousel.min.js' %}"></script>
<!-- <script src="{% static 'home/js/carousel.js' %}"></script> -->
{% endif %}

home/templates/home/carousel_manager.html
{% extends 'home/base.html' %}
{% block content %}
<section class="container">
  {% include 'home/messages.html' %}
  <h2 class="h2 text-center">Carousel Manager</h2>
  <ul id="btnList" class="text-center">
    <li>
      <a class="btn btn-secondary" href="{% url 'home:index' %}">Back to Home Page</a>
    </li>
    <li>
      <a class="btn btn-secondary" href="{% url 'home:carousel-upload' %}">Upload Images</a>
    </li>
    <li>
      <button id="submit" class="btn btn-primary">Save Changes</button>
    </li>
  </ul>
  <ol class="image-list">
    {% for img in images %}
    <li data-id="{{ img.id }}">
      <div class="controls">
        <i class="fas fa-caret-up fa-3x"></i>
        <i class="fas fa-caret-down fa-3x"></i>
      </div>
      <div class="thumbnail-container">
        <a data-fancybox="gallery" href="{{ img.image.url }}">
          <img src="{{ img.thumbnail.url }}" alt="Thumbnail">
        </a>
      </div>
      <div class="btn-container">
        <a href="{% url 'home:carousel-delete' img.id %}" class="btn btn-danger">Delete</a>
      </div>
    </li>
    {% endfor %}
  </ol>
</section>{% load static %}
<!-- <script src="{% static 'home/js/carousel_manager.js' %}"></script> -->
<script src="{% static 'home/js/carousel_manager.min.js' %}"></script>
{% endblock %}

home/templates/home/carousel_upload.html
{% extends 'home/base.html' %}
{% block content %}
<section class="container">
  {% include 'home/messages.html' %}
  <h2 class="h2 text-center">Carousel Upload</h2>
  <form id="carouselUpload" action="{% url 'home:carousel-upload' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="max-width-484 margin-0-auto text-center">
      {{ form.images }}
    </div>
    <ul id="btnList" class="text-center">
      <li>
        <a class="btn btn-secondary" href="{% url 'home:index' %}">Back to Home Page</a>
      </li>
      <li>
        <a class="btn btn-secondary" href="{% url 'home:carousel' %}">Back to Carousel Manager</a>
      </li>
      <li>
        <input class="btn btn-primary" type="submit" value="Upload">
      </li>
    </ul>
  </form>
</section>
{% endblock %}

home/templates/home/footer.html
<footer id="footer">
  <div class="footer-list">
    <ul>
      <li>
        {% if request.user.is_authenticated %}
        <small><a href="{% url 'home:logout' %}">Log Out</a></small>
        {% else %}
        <small><a href="{% url 'home:login' %}">Admin Login</a></small>
        {% endif %}
      </li>
      <li>
        <small><a class="external-link" href="https://github.com/mattmc318/Susan-Kill-Kegan-and-Associates">GitHub</a></small>
      </li>
      <li>
        <small><a class="external-link" href="https://mccarthycode.com/">McCarthy Code</a></small>
      </li>
    </ul>
  </div>
  <small><span class="text-nowrap">&copy; {{ year }}</span> <span class="text-nowrap">{{ name }}.</span> <span class="text-nowrap">All rights reserved.</span></small>
</footer>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% block content %}
{% include 'home/carousel.html' %}
<section class="container">
  {% include 'home/messages.html' %}
  {% if request.user.is_superuser %}
  <ul id="btnList" class="text-center">
    <li>
      <a href="{% url 'home:carousel' %}" class="btn btn-secondary">Carousel  Manager</a>
    </li>
  </ul>
  {% endif %}
  <h3 class="h3 text-center">Overview</h3>
  <p class="text-justify">Since 1985, Susan Kill Kegan &amp; Associates has provided creative solutions in landscape architecture from Lake Forest, IL, to Grand Beach, MI. A wide variety of project areas include single and multi-family residential, commercial, schools and enhancements. Many of these designs have required City of Chicago Landscape Ordinance compliance.</p>
  <p class="text-justify">As stated on the American Society of Landscape Architect's website, landscape architects have been “green since 1899”, dedicated to solving environmental problems through landscape design. Green roofs, bioswales, permeable pavers and other stormwater management solutions are evident in our designs.</p>
  <p class="text-justify">Susan Kill Kegan &amp; Associates' style is client and site driven. Great care is taken to determine objectives and together with existing conditions, develop a landscape plan that is beautiful and functional.</p>
  <h3 class="h3 text-center">Contact</h3>
  <address class="text-center">Susan Kill Kegan, RLA<br>
    9620 South Damen Avenue<br>
    Chicago, IL 60643<br>
    <a href="tel:+17732397119">773 239 7119</a><br>
    <a href="mailto:skeganrla@sbcglobal.net">skeganrla@sbcglobal.net</a>
  </address>
</section>
{% endblock %}

home/templates/home/login.html
{% extends 'home/base.html' %}
{% block content %}
<section class="container">
  {% include 'home/messages.html' %}
  <h2 class="h2 text-center">Admin Login</h2>
  <form class="max-width-400 margin-0-auto" method="POST">
    {% csrf_token %}
    {{ form }}
    <button class="btn btn-primary form-control" type="submit">Login</button>
  </form>
</section>
{% endblock %}

home/templates/home/messages.html
{% if messages %}
{% for message in messages %}
{% if 'error' in message.tags %}
<div class="alert alert-danger" role="alert">
  <a href="javascript:void(0);" class="close" data-dismiss="alert" aria-label="close" title="close">&times;</a>
  <p><i class="fas fa-exclamation-circle"></i> {% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</p>
</div>
{% elif 'success' in message.tags  %}
<div class="alert alert-success" role="alert">
  <a href="javascript:void(0);" class="close" data-dismiss="alert" aria-label="close" title="close">&times;</a>
  <p><i class="fas fa-check-circle"></i> {% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</p>
</div>
{% elif 'info' in message.tags %}
<div class="alert alert-info" role="alert">
  <a href="javascript:void(0);" class="close" data-dismiss="alert" aria-label="close" title="close">&times;</a>
  <p><i class="fas fa-info-circle"></i> {% if 'safe' in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</p>
</div>
{% endif %}
{% endfor %}
{% endif %}

home/templates/home/navbar.html
<nav id="navbar" class="navbar navbar-default navbar-expand-md navbar-dark sticky-top">
  <button id="navbarMenuButton" class="d-md-none ml-auto" type="button">
    <i class="fas fa-bars fa-2x"></i>
  </button>
  <div id="navbarCollapse" class="ml-auto">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:about' %}">About Me</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'gallery:index' %}">Gallery</a>
      </li>
    </ul>
  </div>
</nav>

home/templates/home/title.html
<header id="title">
  <section class="container">
    <a href="{% url 'home:index' %}">
      <h1 class="h1">Susan Kill Kegan & Associates</h2>
      <h4 class="h4"><span class="text-nowrap">Landscape Architecture</span> <span class="bullet">&bull;</span> <span class="text-nowrap">Urban Design</span> <span class="bullet">&bull;</span> <span class="text-nowrap">Site Planning</span></h4>
    </a>
  </section>
</header>