gallery/urls.py
from django.urls import re_path

from . import views
from skka.settings import DEBUG

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^manager/$', views.manager, name='manager'),
    re_path(r'^upload/$', views.upload, name='upload'),
    re_path(r'^reorder/$', views.reorder, name='reorder'),
    re_path(r'^delete/(?P<img_id>[1-9]\d*)/$', views.delete, name='delete'),
]

home/urls.py
from django.urls import re_path

from . import views
from skka.settings import DEBUG

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^about/$', views.about, name='about'),
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^logout/$', views.logout, name='logout'),
    re_path(r'^carousel/$', views.carousel_manager, name='carousel'),
    re_path(r'^carousel/upload/', views.carousel_upload, name='carousel-upload'),
    re_path(r'^carousel/reorder/', views.carousel_reorder, name='carousel-reorder'),
    re_path(r'^carousel/delete/(?P<img_id>[1-9]\d*)/', views.carousel_delete, name='carousel-delete'),
]

if DEBUG:
    urlpatterns += [
        re_path(r'^400/$', views.handler400),
        re_path(r'^403/$', views.handler403),
        re_path(r'^404/$', views.handler404),
        re_path(r'^500/$', views.handler500),
    ]

skka/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf.urls import (
    handler400,
    handler403,
    handler404,
    handler500,
)
from django.conf.urls.static import static

from skka.settings import DEBUG, MEDIA_URL, MEDIA_ROOT

urlpatterns = [
    re_path(r'^', include(('home.urls', 'home'), namespace='home')),
    re_path(r'^gallery/', include(('gallery.urls', 'gallery'), namespace='gallery')),
    re_path(r'^admin/', admin.site.urls),
]

if DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

handler400 = 'home.views.handler400'
handler403 = 'home.views.handler403'
handler404 = 'home.views.handler404'
handler500 = 'home.views.handler500'

gallery/models.py
from django.db import models

from home.models import ThumbnailedImage

class GalleryImage(ThumbnailedImage):
    CATEGORY_CHOICES = [
        (0, 'Residential'),
        (1, 'Commercial'),
        (2, 'Schools'),
        (3, 'Enhancements'),
        (4, 'Sustainability'),
    ]

    category = models.PositiveSmallIntegerField(choices=CATEGORY_CHOICES)

    def relative_path(instance, filename):
        return 'gallery/%s/%s' % (instance.CATEGORY_CHOICES[instance.category][1].lower(), filename)

    image = models.ImageField(blank=True, null=True, default=None, upload_to=relative_path)
    thumbnail = models.ImageField(blank=True, null=True, default=None, upload_to=relative_path)

    def image_ops(self):
        super().image_ops(
            relative_path=self.relative_path(''), max_size=(3600, 2250)
        )

gallery/forms.py
from django import forms

from .models import GalleryImage

class GalleryForm(forms.ModelForm):
    images = forms.ImageField(
        label='Image',
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
    )

    category = forms.ChoiceField(
        label='Category',
        choices=GalleryImage.CATEGORY_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'}),
    )

    def clean(self):
        super().clean()
        cleaned_data = self.cleaned_data

        cleaned_data['category'] = int(cleaned_data['category'])

        return cleaned_data

    class Meta:
        model = GalleryImage
        fields = ['image', 'category']

gallery/views.py
import json

from datetime import datetime

from django.contrib import messages
from django.shortcuts import (
    get_object_or_404,
    redirect,
    render,
    reverse,
)
from django.http import (
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseNotFound,
)

from .models import GalleryImage
from .forms import GalleryForm
from skka.settings import TZ, NAME

def index(request):
    if request.method != 'GET':
        return HttpResponseBadRequest()

    images_by_category = []
    for category_id, name in GalleryImage.CATEGORY_CHOICES:
        images = GalleryImage.objects.filter(category=category_id).order_by('date_updated')

        if images:
            images_by_category.append({
                'id': category_id,
                'name': name,
                'images': images,
            })

    return render(request, 'gallery/index.html', {
        'images_by_category': images_by_category,
        'year': datetime.now(TZ).year,
        'name': NAME,
    })

def manager(request):
    if not (request.method == 'GET' and request.user.is_superuser):
        return HttpResponseBadRequest()

    images_by_category = []
    for category_id, name in GalleryImage.CATEGORY_CHOICES:
        images = GalleryImage.objects.filter(category=category_id).order_by('date_updated')

        if images:
            images_by_category.append({
                'id': category_id,
                'name': name,
                'images': images,
            })

    return render(request, 'gallery/manager.html', {
        'images_by_category': images_by_category,
        'year': datetime.now(TZ).year,
        'name': NAME,
    })

def upload(request):
    if not request.user.is_superuser:
        return HttpResponseBadRequest()

    if request.method == 'GET':
        return render(request, 'gallery/upload.html', {
            'form': GalleryForm(),
            'year': datetime.now(TZ).year,
            'name': NAME,
        })
    elif request.method == 'POST':
        form = GalleryForm(request.POST, request.FILES)

        if form.is_valid():
            img_form = form.save(commit=False)

            images = request.FILES.getlist('images')
            category = img_form.category
            for img in images:
                image = GalleryImage.create(image=img, category=category)
                image.save()

            images_len = len(images)
            messages.success(request, 'You have successfully added %d image%s to the gallery.' % (images_len, '' if images_len == 1 else 's'))

            return redirect('gallery:upload')

        messages.error(request, 'There was an error adding the image to the gallery.')

        return redirect('gallery:upload')

    return HttpResponseBadRequest()

def reorder(request):
    if not (request.method == 'GET' and request.user.is_superuser):
        return HttpResponseBadRequest()

    # retrieve lists
    orders = json.loads(request.GET.get('orders'))

    # validate input
    for category in orders:
        for img in GalleryImage.objects.filter(category=category['id']):
            if img.id not in category['order']:
                messages.error(request, 'There was an error reordering the gallery images. At least one of the images specified could not be found.')

                return HttpResponseNotFound()

    # touch images in order
    for category in orders:
        for img_id in category['order']:
            img = GalleryImage.objects.get(id=img_id).save()

    messages.success(request, 'You have successfully reordered the gallery images. <a href="%s">Click here</a> to see the updated gallery.' % reverse('gallery:index'), extra_tags='safe')

    return HttpResponse(status=200)

def delete(request, img_id):
    if not (request.method == 'GET' and request.user.is_superuser):
        return HttpResponseBadRequest()

    img = get_object_or_404(GalleryImage, id=img_id)
    img.delete()

    messages.success(request, 'You have successfully deleted the gallery image.')

    return redirect('gallery:manager')

gallery/templates/gallery/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Meta Tags -->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Title & Favicon -->
  <title>Susan Kill Kegan &ndash; Registered Landscape Architect</title>
  <link rel="shortcut icon" href="{% load static %}{% static 'home/img/favicon.png' %}" type="image/x-icon">

  <!--------------->
  <!--Stylesheets-->
  <!--------------->

  <!-- Internal Stylesheets (compressed) -->

  <!-- Reset CSS -->
  <link rel="stylesheet" href="{% static 'home/css/reset.min.css' %}">

  <!-- Gallery App CSS -->
  <link rel="stylesheet" href="{% static 'gallery/css/gallery.min.css' %}">

  <!--Internal Stylesheets (uncompressed)-->

  <!-- Reset CSS -->
  <!-- <link rel="stylesheet" href="{% static 'home/css/reset.css' %}"> -->

  <!-- Gallery App CSS -->
  <!-- <link rel="stylesheet" href="{% static 'gallery/css/gallery.css' %}"> -->

  <!-- External Stylesheet Libraries (compressed) -->

  <!-- Font Awesome CSS -->
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!-- fancybox CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css">

  <!----------->
  <!--Scripts-->
  <!----------->

  <!-- External Script Libraries (compressed) -->

  <!-- Font Awesome JS -->
  <script type="text/javascript" src="https://kit.fontawesome.com/3c68f13de5.js"></script>

  <!-- jQuery JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

  <!-- Bootstrap JS -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <!-- fancybox JS -->
  <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>

  <!-- Internal Scripts (compressed) -->

  <!-- Cross-App JS -->
  <script type="text/javascript" src="{% static 'global/js/global.min.js' %}"></script>

  <!-- Gallery App JS -->
  <script type="text/javascript" src="{% static 'gallery/js/gallery.min.js' %}"></script>

  <!-- Internal Scripts (uncompressed) -->

  <!-- Cross-App JS -->
  <!-- <script type="text/javascript" src="{% static 'global/js/global.js' %}"></script> -->

  <!-- Gallery App JS -->
  <!-- <script type="text/javascript" src="{% static 'gallery/js/gallery.js' %}"></script> -->
</head>
<body>
  <section id="grid">
    {% include 'home/title.html' %}
    <section id="content">
      {% include 'home/navbar.html' %}
      {% block content %}
      {% endblock %}
      {% include 'home/footer.html' %}
    </section>
  </section>
</body>
</html>

gallery/templates/gallery/index.html
{% extends 'gallery/base.html' %}
{% block content %}
<section class="container">
  <h2 class="h2 text-center">Gallery</h2>
  {% if request.user.is_superuser %}
  <ul id="btnList" class="text-center">
    <li>
      <a href="{% url 'gallery:manager' %}" class="btn btn-secondary">Gallery Manager</a>
    </li>
  </ul>
  {% endif %}
  {% for category in images_by_category %}
  {% if category.images %}
  <h3 class="h3 text-center">{{ category.name }}</h3>
  <ul class="gallery-list">
  {% for img in category.images %}
    <li class="thumbnail-container">
      <a data-fancybox="gallery" href="{{ img.image.url }}">
        <img src="{{ img.image.url }}">
      </a>
    </li>
  {% endfor %}
  </ul>
  {% endif %}
  {% empty %}
  <p class="empty">There are no images to show at this time.</p>
  {% endfor %}
</section>
{% endblock %}

gallery/templates/gallery/manager.html
{% extends 'gallery/base.html' %}
{% block content %}
<section class="container">
  {% include 'home/messages.html' %}
  <h2 class="h2 text-center">Gallery Manager</h2>
  <ul id="btnList" class="text-center">
    <li>
      <a href="{% url 'gallery:index' %}" class="btn btn-secondary">Back to Gallery</a>
    </li>
    <li>
      <a href="{% url 'gallery:upload' %}" class="btn btn-secondary">Upload Images</a>
    </li>
    <li>
      <button id="submit" class="btn btn-primary">Save Changes</button>
    </li>
  </ul>
  {% for category in images_by_category %}
  {% if category.images %}
  <h3 class="h3 text-center">{{ category.name }}</h3>
  <ol class="image-list" data-id="{{ category.id }}">
  {% for img in category.images %}
    <li data-id="{{ img.id }}">
      <div class="controls">
        <i class="fas fa-caret-up fa-3x"></i>
        <i class="fas fa-caret-down fa-3x"></i>
      </div>
      <div class="thumbnail-container">
        <a data-fancybox="gallery" href="{{ img.image.url }}">
          <img src="{{ img.thumbnail.url }}" alt="Thumbnail">
        </a>
      </div>
      <div class="btn-container">
        <a href="{% url 'gallery:delete' img.id %}" class="btn btn-danger">Delete</a>
      </div>
    </li>
  {% endfor %}
  </ol>
  {% endif %}
  {% empty %}
  <p class="empty">There are no images to show at this time.</p>
  {% endfor %}
</section>
{% endblock %}

gallery/templates/gallery/upload.html
{% extends 'gallery/base.html' %}
{% block content %}
<section class="container">
  {% include 'home/messages.html' %}
  <form id="galleryUpload" action="{% url 'gallery:upload' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h2 class="h2 text-center">Gallery Upload</h2>
    <div class="max-width-436 margin-0-auto text-center">
      {{ form.category }}
      {{ form.images }}
    </div>
    <ul id="btnList" class="text-center">
      <li>
        <a href="{% url 'gallery:index' %}" class="btn btn-secondary">Back to Gallery</a>
      </li>
      <li>
        <a href="{% url 'gallery:manager' %}" class="btn btn-secondary">Back to Gallery Manager</a>
      </li>
      <li>
        <input class="btn btn-primary" type="submit" value="Upload">
      </li>
    </ul>
  </form>
</section>
{% endblock %}